In [ ]:
import numpy as np
import pickle
from scipy.sparse import coo_matrix, csr_matrix
import json
from collections import Counter

attr_path = '/home1/workspace/mengjunjie/lightgcn/data/yelp/preference.txt'
# id2user_path = '/home1/workspace/mengjunjie/lightgcn/data/amazon-book/id2user.json'
# id2item_path = '/home1/workspace/mengjunjie/lightgcn/data/amazon-book/id2item.json'
output_path = 'yelp/attr_edges.pkl'
attr_edges = []
attr_counter = Counter()
with open(attr_path, 'r') as f:
    for line in f:
        item, attr = line.split(' ')
        attr_edges.append((int(item), int(attr)))
        attr_counter[int(attr)] += 1


In [24]:
# filter
print(len(attr_edges))
# filtered_attr_edges = [(item, attr) for item, attr in attr_edges if attr_counter[attr] >= 15 and attr_counter[attr] <= 3000]
# attr_edges = filtered_attr_edges
# print(len(attr_edges))

170516


In [25]:

print(attr_edges[:5])  # Display first 5 edges for verification
## transfer to coo_matrix 
item_ids, attr_ids = zip(*attr_edges)

item_ids = np.array(item_ids)
attr_ids = np.array(attr_ids)
user_item_num = max(item_ids) + 1
# with open(id2item_path, 'r') as f1,\
#      open(id2user_path, 'r') as f2 :
#     id2item = json.load(f1)
#     id2user = json.load(f2)
# user_item_num = len(id2user) + len(id2item)

print(user_item_num)
print(max(attr_ids)+1)

attr_edges = coo_matrix((np.ones(len(item_ids)), (item_ids, attr_ids)), shape=(user_item_num, max(attr_ids) + 1))
with open(output_path, 'wb') as f:
    pickle.dump(attr_edges, f)

[(1364, 540), (2140, 7), (5598, 635), (4918, 876), (3082, 1429)]
10799
4065


In [ ]:

with open(output_path, 'rb') as f:
    loaded_attr_edges = pickle.load(f)
print(loaded_attr_edges.shape)


In [2]:
import pickle
attr_path = '/home1/workspace/mengjunjie/RLMRec/data/steam/attr_edges.pkl'
with open(attr_path, 'rb') as f:
    attr_edges = pickle.load(f)
print(attr_edges.shape)

(28546, 1246)


In [4]:
from scipy.sparse import csr_matrix

loaded_attr_edges = csr_matrix(attr_edges)  # Convert to CSR format for efficient operations
print(loaded_attr_edges[:2])  # Display first 2 rows for verification

AttributeError: nnz not found

In [22]:
trn_mat = '/home1/workspace/mengjunjie/RLMRec/data/amazon/trn_mat.pkl'
with open(trn_mat, 'rb') as f:
    trn_mat = pickle.load(f)
print('trn_mat shape:', trn_mat.shape)
trn_mat = np.array(trn_mat.todense())
print(trn_mat[:5][:5])

trn_mat shape: (11000, 9332)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
